import csv

# Dataset gồm 100 câu (copy dataset từ trên)
dataset = [
    # ----------- place_order (50 câu) -----------
    {"text": "Tôi muốn mua 2 quyển Naruto tập 20, giao tới Hà Nội, số 0909123456", "label": "place_order"},
    {"text": "Đặt mua sách One Piece tập 10, số điện thoại 0912345678, giao tại TP HCM", "label": "place_order"},
    {"text": "Tôi muốn mua Không gia đình, 1 quyển", "label": "place_order"},
    {"text": "Mua 3 cuốn Tuyển tập thơ mùa hạ, giao Hà Nội", "label": "place_order"},
    {"text": "Đặt sách Đàn ông sao Hỏa đàn bà sao Kim, số điện thoại 0909988776", "label": "place_order"},
    {"text": "Tôi muốn mua 1 cuốn Naruto tập 20", "label": "place_order"},
    {"text": "Mua sách One Piece tập 10 và giao tới Quảng Ninh", "label": "place_order"},
    {"text": "Đặt mua Không gia đình, số lượng 2, địa chỉ Hà Nội", "label": "place_order"},
    {"text": "Tôi muốn mua 1 Tuyển tập thơ mùa hạ", "label": "place_order"},
    {"text": "Mua sách Đàn ông sao Hỏa đàn bà sao Kim, số điện thoại 0911223344", "label": "place_order"},
    {"text": "Tôi muốn mua Naruto tập 20, giao tận nơi", "label": "place_order"},
    {"text": "Đặt 2 quyển One Piece tập 10", "label": "place_order"},
    {"text": "Mua Không gia đình, 1 quyển, địa chỉ TP HCM", "label": "place_order"},
    {"text": "Tôi muốn mua Tuyển tập thơ mùa hạ, số lượng 3", "label": "place_order"},
    {"text": "Đặt sách Đàn ông sao Hỏa đàn bà sao Kim, giao Hà Nội", "label": "place_order"},
    {"text": "Mua Naruto tập 20, số điện thoại 0909111222", "label": "place_order"},
    {"text": "Tôi muốn mua 1 quyển One Piece tập 10", "label": "place_order"},
    {"text": "Đặt mua Không gia đình, giao TP HCM", "label": "place_order"},
    {"text": "Mua 2 cuốn Tuyển tập thơ mùa hạ", "label": "place_order"},
    {"text": "Tôi muốn mua Đàn ông sao Hỏa đàn bà sao Kim", "label": "place_order"},
    {"text": "Đặt mua Naruto tập 20, số điện thoại 0912345678", "label": "place_order"},
    {"text": "Mua One Piece tập 10, giao tận nơi", "label": "place_order"},
    {"text": "Tôi muốn mua 3 cuốn Không gia đình", "label": "place_order"},
    {"text": "Đặt 1 Tuyển tập thơ mùa hạ", "label": "place_order"},
    {"text": "Mua Đàn ông sao Hỏa đàn bà sao Kim, số lượng 2", "label": "place_order"},
    {"text": "Tôi muốn đặt Naruto tập 20", "label": "place_order"},
    {"text": "Đặt mua 2 cuốn One Piece tập 10, giao tại Hà Nội", "label": "place_order"},
    {"text": "Mua Không gia đình, số điện thoại 0909001122", "label": "place_order"},
    {"text": "Tôi muốn mua 1 Tuyển tập thơ mùa hạ, giao TP HCM", "label": "place_order"},
    {"text": "Đặt sách Đàn ông sao Hỏa đàn bà sao Kim, số lượng 1", "label": "place_order"},
    {"text": "Mua Naruto tập 20, giao tới Quảng Ninh", "label": "place_order"},
    {"text": "Tôi muốn mua 2 cuốn One Piece tập 10", "label": "place_order"},
    {"text": "Đặt mua Không gia đình, giao tận nơi", "label": "place_order"},
    {"text": "Mua Tuyển tập thơ mùa hạ, số điện thoại 0909123456", "label": "place_order"},
    {"text": "Tôi muốn mua 1 quyển Đàn ông sao Hỏa đàn bà sao Kim", "label": "place_order"},
    {"text": "Đặt mua Naruto tập 20, số lượng 3", "label": "place_order"},
    {"text": "Mua One Piece tập 10, giao Hà Nội", "label": "place_order"},
    {"text": "Tôi muốn mua 2 cuốn Không gia đình", "label": "place_order"},
    {"text": "Đặt 1 Tuyển tập thơ mùa hạ, giao TP HCM", "label": "place_order"},
    {"text": "Mua Đàn ông sao Hỏa đàn bà sao Kim, số điện thoại 0911223344", "label": "place_order"},
    {"text": "Tôi muốn đặt Naruto tập 20, số lượng 2", "label": "place_order"},
    {"text": "Đặt mua 1 cuốn One Piece tập 10, giao tận nơi", "label": "place_order"},
    {"text": "Mua Không gia đình, số điện thoại 0909001122", "label": "place_order"},
    {"text": "Tôi muốn mua 3 cuốn Tuyển tập thơ mùa hạ", "label": "place_order"},
    {"text": "Đặt 1 Đàn ông sao Hỏa đàn bà sao Kim", "label": "place_order"},
    {"text": "Mua Naruto tập 20, giao tới Hà Nội", "label": "place_order"},
    {"text": "Tôi muốn mua 1 One Piece tập 10", "label": "place_order"},
    {"text": "Đặt mua Không gia đình, số lượng 2", "label": "place_order"},
    {"text": "Mua 2 cuốn Tuyển tập thơ mùa hạ, giao TP HCM", "label": "place_order"},
    {"text": "Tôi muốn mua Đàn ông sao Hỏa đàn bà sao Kim", "label": "place_order"},
    {"text": "Đặt mua Naruto tập 20, số điện thoại 0909111222", "label": "place_order"},

    # ----------- detail_book (50 câu) -----------
    {"text": "Có sách Naruto không?", "label": "detail_book"},
    {"text": "Cho tôi biết giá của One Piece tập 10", "label": "detail_book"},
    {"text": "Số lượng tồn kho Không gia đình còn bao nhiêu?", "label": "detail_book"},
    {"text": "Thông tin Tuyển tập thơ mùa hạ", "label": "detail_book"},
    {"text": "Đàn ông sao Hỏa đàn bà sao Kim còn bán không?", "label": "detail_book"},
    {"text": "Tôi muốn biết tác giả của Naruto tập 20", "label": "detail_book"},
    {"text": "Cho tôi biết thể loại One Piece tập 10", "label": "detail_book"},
    {"text": "Sách Không gia đình giá bao nhiêu?", "label": "detail_book"},
    {"text": "Có Tuyển tập thơ mùa hạ không?", "label": "detail_book"},
    {"text": "Thông tin Đàn ông sao Hỏa đàn bà sao Kim", "label": "detail_book"},
    {"text": "Sách Naruto tập 20 còn không?", "label": "detail_book"},
    {"text": "Tác giả One Piece tập 10 là ai?", "label": "detail_book"},
    {"text": "Giá Không gia đình là bao nhiêu?", "label": "detail_book"},
    {"text": "Tồn kho Tuyển tập thơ mùa hạ còn bao nhiêu?", "label": "detail_book"},
    {"text": "Thể loại Đàn ông sao Hỏa đàn bà sao Kim là gì?", "label": "detail_book"},
    {"text": "Có bán Naruto tập 20 không?", "label": "detail_book"},
    {"text": "Tác giả One Piece tập 10 là ai?", "label": "detail_book"},
    {"text": "Thông tin chi tiết Không gia đình", "label": "detail_book"},
    {"text": "Tồn kho Tuyển tập thơ mùa hạ hiện tại?", "label": "detail_book"},
    {"text": "Sách Đàn ông sao Hỏa đàn bà sao Kim còn không?", "label": "detail_book"},
    {"text": "Naruto tập 20 giá bao nhiêu?", "label": "detail_book"},
    {"text": "Cho tôi biết tác giả One Piece tập 10", "label": "detail_book"},
    {"text": "Không gia đình thuộc thể loại gì?", "label": "detail_book"},
    {"text": "Thông tin Tuyển tập thơ mùa hạ", "label": "detail_book"},
    {"text": "Đàn ông sao Hỏa đàn bà sao Kim còn bán không?", "label": "detail_book"},
    {"text": "Sách Naruto tập 20 còn tồn kho không?", "label": "detail_book"},
    {"text": "Tác giả One Piece tập 10 là ai?", "label": "detail_book"},
    {"text": "Giá Không gia đình hiện nay?", "label": "detail_book"},
    {"text": "Tồn kho Tuyển tập thơ mùa hạ bao nhiêu?", "label": "detail_book"},
    {"text": "Thể loại Đàn ông sao Hỏa đàn bà sao Kim là gì?", "label": "detail_book"},
    {"text": "Có bán Naruto tập 20 không?", "label": "detail_book"},
    {"text": "Tác giả One Piece tập 10 là ai?", "label": "detail_book"},
    {"text": "Thông tin chi tiết Không gia đình", "label": "detail_book"},
    {"text": "Tồn kho Tuyển tập thơ mùa hạ còn bao nhiêu?", "label": "detail_book"},
    {"text": "Sách Đàn ông sao Hỏa đàn bà sao Kim còn không?", "label": "detail_book"},
    {"text": "Naruto tập 20 giá bao nhiêu?", "label": "detail_book"},
    {"text": "Cho tôi biết tác giả One Piece tập 10", "label": "detail_book"},
    {"text": "Không gia đình thuộc thể loại gì?", "label": "detail_book"},
    {"text": "Thông tin Tuyển tập thơ mùa hạ", "label": "detail_book"},
    {"text": "Đàn ông sao Hỏa đàn bà sao Kim còn bán không?", "label": "detail_book"},
    {"text": "Sách Naruto tập 20 còn tồn kho không?", "label": "detail_book"},
    {"text": "Tác giả One Piece tập 10 là ai?", "label": "detail_book"},
    {"text": "Giá Không gia đình hiện nay?", "label": "detail_book"},
    {"text": "Tồn kho Tuyển tập thơ mùa hạ bao nhiêu?", "label": "detail_book"},
    {"text": "Thể loại Đàn ông sao Hỏa đàn bà sao Kim là gì?", "label": "detail_book"},
    {"text": "Có bán Naruto tập 20 không?", "label": "detail_book"},
    {"text": "Tác giả One Piece tập 10 là ai?", "label": "detail_book"},
    {"text": "Thông tin chi tiết Không gia đình", "label": "detail_book"},
]


# Ghi CSV
with open("bookstore_dataset.csv", mode="w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=["text", "label"])
    writer.writeheader()
    for row in dataset:
        writer.writerow(row)

print("Đã lưu dataset vào bookstore_dataset.csv")
